---
- src: geerlingguy.firewall
- src: geerlingguy.ntp
- src: geerlingguy.git
- src: geerlingguy.java
- src: https://github.com/alexanderfournierdemos/ansible-role-jenkins
  version: master
  name: jenkins
